config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :images
  get 'home/index'

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

	validates_presence_of :user_id, :image_file
	validates_inclusion_of :public, :in => [true, false]

	belongs_to :user

	has_one_attached :image_file

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /images or /images.json
  def index
    if (current_user)
      @images = Image.where(user_id: current_user.id).or(Image.where(public: true)).order(id: :desc)
    else
      @images = Image.where(public: true).order(id: :desc)
    end


  end

  # GET /images/1 or /images/1.json
  def show
    @username = User.find(@image.user_id).email 
  end

  # GET /images/new
  def new
    @image = current_user.images.build
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = current_user.images.build(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @image = current_user.images.find_by(id: params[:id])
    redirect_to images_path, notice: "403: unauthorized" if @image.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:user_id, :description, :public, :image_file)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f7df8f;">
  <div class="container-fluid">
  	<%= link_to 'imij!', root_path, class:"navbar-brand" %>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
      	<%= link_to 'browse', images_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
	      <li class="nav-item">
	      	<%= link_to 'profile', edit_user_registration_path, class:"nav-link" %>
	      </li>
	      <li class="nav-item">
	      	<%= link_to 'sign out', destroy_user_session_path, method: :delete, class:"nav-link" %>
	      </li>
	    <% else %>
	    	<li class="nav-item">
	      	<%= link_to 'sign up', new_user_registration_path, class:"nav-link" %>
	      </li>
	      <li class="nav-item">
	      	<%= link_to 'sign in', new_user_session_path, class:"nav-link" %>
	      </li>
	    <% end %>
    </ul>
    <span class="navbar-text">
      intern matthew's image juxtaposer!
    </span>
  </div>
</nav>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>imij</h1>
<p>intern matthew's image juxtaposer!</p>

<p>click browse to view the repository</p>
<p>or log in to get started C/R/U/D'ing your own images!</p>

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.file_field :image_file, class: "form-control", accept: "image/gif, image/jpeg, image/png" %>
  </div>

  <div class="field">
    <%= form.text_area :description, class: "form-control", placeholder: "description" %>
  </div>

  <div class="field">
    <%= form.label "public?", class: "form-check-label" %>
    <%= form.check_box :public, class: "form-check-input", value: false %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :image_user_id, type: :hidden, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_thumbnails.html.erb
<div class="container-fluid">
  <% @images.each do |image| %>
    <%= link_to image do %>
      <%= image_tag image.image_file.variant(resize_to_fill: [200, 200]), class: "img-thumbnail", style: "padding: 0.1rem" %>
    <% end %>
  <% end %>
</div>

app/views/images/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>editing image</h1>

<%= render 'form', image: @image %>

<%= link_to 'show', @image %> |
<%= link_to 'destroy', @image, method: :delete, data: { confirm: 'are you sure?' } %> |
<%= link_to 'back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1>repository</h1>
  <%= link_to 'new image', new_image_path %>
</div>

</br>

<%= render "images/thumbnails" %>

<br>

app/views/images/new.html.erb
<p id="notice"><%= notice %></p>

<h1>new image</h1>

<%= render 'form', image: @image %>

<%= link_to 'back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center container-fluid">
  <%= image_tag @image.image_file, class:"img-fluid" %>
</div>

<p>
  <strong>description:</strong>
  <%= @image.description %>
</p>
<p>
  <strong>uploaded by:</strong>
    <%= @username %>
    <% if @image.public == false %>
      (private)
    <% end %>

</p>

<% if @image.user == current_user %>
  <%= link_to 'edit', edit_image_path(@image) %> |
  <%= link_to 'destroy', @image, method: :delete, data: { confirm: 'are you sure?' } %> |
<% end %>
<%= link_to 'back', images_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>imij!</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <br>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>